legend = {
    "Distacco": [
        "Sono costretto, è un ricatto, mi costringe, sono deluso, sono sorpreso, cado dalle nuvole, non me l'aspettavo, è strano, non mi degna di…",
        "Ricorro a tribunale/avvocato",
        "Non mi sta seguendo…",
        "Per l'ennesima volta… / detto già n volte",
        "Le ripeto…",
        "'allora però…'",
        "'va beh'",
        "Non capisco per quale motivo…",
        "Pensavo di essere a posto",
        "A questo punto…",
        "Le sto dicendo/spiegando",
        "Non si fa cosi",
        "Non mi trovo…"
    ],
    "Incertezza": [
        "In teoria...",
        "Non so, non ricordo",
        "Provo a, verifico",
        "Non sono sicuro/certo",
        "Verbi condizionali",
        "...giusto?/...vero?"
    ],
    "Preoccupazione": [
        "Angoscia",
        "essere in pensiero",
        "avere paura",
        "essere preoccupato",
        "avere ansia",
        "attacco di panico",
        "Essere in difficoltà"
    ],
    "Rabbia": [
        "Insulti",
        "volgarità",
        "Scorrettezza",
        "sono nervoso",
        "infastidito",
        "lei mi provoca",
        "disturbare",
        "È una truffa",
        "sono stato fregato",
        "Sono infuriato"
    ],
    "Sconforto": [
        "Purtroppo",
        "sfortunatamente",
        "malauguratamente",
        "Mi dispiace",
        "mi scuso",
        "per pietà",
        "chiedo perdono",
        "abbia compassione",
        "Si metta nei miei panni",
        "È un momento difficile",
        "Non ce la faccio"
    ],
    "Sintonia": [
        "Felice",
        "contento",
        "tranquillizzare",
        "sollevare",
        "alleviare",
        "togliere un peso",
        "Certo",
        "accontentare",
        "fiducia",
        "onorare",
        "rassicurante",
        "consentire",
        "ringraziare",
        "grazie",
        "A posto",
        "Giusto",
        "vero",
        "Ha ragione",
        "Va bene",
        "bene",
        "Sentire meglio",
        "stare meglio",
        "Diminutivi",
        "Buono",
        "gentile",
        "disponibile"
    ]
}
